// Mocks generated by Mockito 5.4.4 from annotations
// in fit_master/test/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:fit_master/src/core/network/BaseApiService.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BaseApisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseApisService extends _i1.Mock implements _i2.BaseApisService {
  MockBaseApisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> getApiResponse(
    String? url,
    String? token, {
    Map<String, String>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApiResponse,
          [
            url,
            token,
          ],
          {#params: params},
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> postApiResponse(
    String? url,
    dynamic data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApiResponse,
          [
            url,
            data,
            token,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> putApiResponse(
    String? url,
    dynamic data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putApiResponse,
          [
            url,
            data,
            token,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> fileApiResponse(
    String? url,
    _i4.File? data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fileApiResponse,
          [
            url,
            data,
            token,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
